[pytest]
markers =
    smoke_test: quick tests to check basic functionality
    step_3: tests to check the functionality from step #3
    tasks_test: tests to check the functionality from step #
    step_4: tests to check all functionalities from step #4
    step_4_viewList: tests to check the functionality from step #4
    step_4_createUser: tests to check the functionality from step #4
    step_4_editUser: tests to check the functionality from step #4
    step_4_deleteOne: tests to check the functionality from step #4
    step_4_deleteAll: tests to check the functionality from step #4
    step_5: tests to check all functionalities from step #5
    step_5_viewList: tests to check the functionality from step #5
    step_5_createStatus: tests to check the functionality from step #5
    step_5_editStatus: tests to check the functionality from step #5
    step_5_deleteOne: tests to check the functionality from step #5
    step_5_deleteAll: tests to check the functionality from step #5
